# Generated by Django 4.1.4 on 2022-12-22 09:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('employee_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='blog.employee')),
                ('title', models.CharField(max_length=100)),
                ('words', models.IntegerField()),
            ],
            options={
                'db_table': 'post',
            },
            bases=('blog.employee',),
        ),
    ]
