# Generated by Django 4.1.4 on 2023-02-27 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cbv', '0002_addphoto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('ingredients', models.CharField(max_length=100)),
                ('instructions', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'recipe',
            },
        ),
    ]
