# Generated by Django 4.1.4 on 2023-03-01 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cbv', '0003_recipe'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('quantity', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'product2',
            },
        ),
    ]
